# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bugtype
brief-intro:  Fullstack Engineer
baseurl: "/tech" # the subpath of your site, e.g. /blog
url: "https://bugtype.github.io/tech" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
# twitter_username: bugtype
# facebook_username: bugtype
github_username:  bugtype
email: bugtype@126.com
weibo_username: bugtype
zhihu_username: bugtype
linkedIn_username: bugtype
dribbble_username:

description_footer: Welcome hahah！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: bugtype

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: cf8506e0ef223e57ff6239944e5####
# google_analytics_id: UA-72449510-# # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: tech/category/
tag_dir: tech/tag/
quick_dir: tech/quick/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
